import { id } from "date-fns/locale";

export const initialState = {
  users: [
    {
      id: 1,
      firstName: 'John',
      secundoName: '',
      lastName: 'Doe',
      secundoSurname: 'Doe',
      identification: '123456789',
      gender: 'Male',
      program: 'Ingenieria de sistemas',
      email: 'jhon@r.com',
      phoneNumber: '123456789',
      role: 'admin',
    },
    {
      id: 2,
      firstName: 'Jane',
      secundoName: '',
      lastName: 'Stone',
      secundoSurname: 'Gallego',
      identification: '123456789',
      gender: 'Famale',
      program: 'Ingenieria de sistemas',
      email: 'jane@r.com',
      phoneNumber: '123456789',
      role: 'Student',
    },
    {
      id: 3,
      firstName: 'Jhonny',
      secundoName: '',
      lastName: 'Jackson',
      secundoSurname: 'Doe',
      identification: '123456789',
      gender: 'Male',
      program: 'Ingenieria de sistemas',
      email: 'jhonny@r.com',
      phoneNumber: '123456789',
      role: 'Student',
    },
    {
      id: 4,
      firstName: 'Jhonny',
      secundoName: '',
      lastName: 'Jackson',
      secundoSurname: 'Doe',
      identification: '123456789',
      gender: 'Male',
      program: 'Ingenieria de sistemas',
      email: 'jhonny@r.com',
      phoneNumber: '123456789',
      role: 'Student',
    },
    {
      id: 5,
      firstName: 'Jhonny',
      secundoName: '',
      lastName: 'Jackson',
      secundoSurname: 'Doe',
      identification: '123456789',
      gender: 'Male',
      program: 'Ingenieria de sistemas',
      email: 'jhonny@r.com',
      phoneNumber: '123456789',
      role: 'Student',
    }
  ],
  userSelected: {},
  loading: false,
  error: false
}