export const initialState = {
  users: [
    {
      id: 1,
      firstName: 'John',
      secondName: '',
      lastName: 'Doe',
      secondSurname: 'Doe',
      identification: '123456789',
      gender: 'Male',
      program: 'Ingenieria de sistemas',
      email: 'jhon@r.com',
      phoneNumber: '123456789',
      role: 'Administrador',
    },
    {
      id: 2,
      firstName: 'Jane',
      secondName: '',
      lastName: 'Stone',
      secondSurname: 'Gallego',
      identification: '123456789',
      gender: 'Famale',
      program: 'Ingenieria de sistemas',
      email: 'jane@r.com',
      phoneNumber: '123456789',
      role: 'Estudiante',
    },
    {
      id: 3,
      firstName: 'Jhonny',
      secondName: '',
      lastName: 'Jackson',
      secondSurname: 'Doe',
      identification: '123456789',
      gender: 'Male',
      program: 'Ingenieria de sistemas',
      email: 'jhonny@r.com',
      phoneNumber: '123456789',
      role: 'Estudiante',
    },
    {
      id: 4,
      firstName: 'Jhonny',
      secondName: '',
      lastName: 'Jackson',
      secondSurname: 'Doe',
      identification: '123456789',
      gender: 'Male',
      program: 'Ingenieria de sistemas',
      email: 'jhonny@r.com',
      phoneNumber: '123456789',
      role: 'Estudiante',
    },
    {
      id: 5,
      firstName: 'Jhonny',
      secondName: '',
      lastName: 'Jackson',
      secondSurname: 'Doe',
      identification: '123456789',
      gender: 'Male',
      program: 'Ingenieria de sistemas',
      email: 'jhonny@r.com',
      phoneNumber: '123456789',
      role: 'Estudiante',
    },
    {
      id: 6,
      firstName: 'Pedro',
      secondName: '',
      lastName: 'Perez',
      secondSurname: 'Doe',
      identification: '123456789',
      gender: 'Male',
      program: 'Derecho',
      email: 'pepit@r.com',
      phoneNumber: '123456789',
      role: 'Estudiante',
    },
    {
      id: 7,
      firstName: 'Juan',
      secondName: '',
      lastName: 'Perez',
      secondSurname: 'Doe',
      identification: '123456789',
      gender: 'Male',
      program: 'Psicologia',
      email: 'juan@r.com',
      phoneNumber: '123456789',
      role: 'Estudiante',
    }
  ],
  userSelected: {},
  loading: false,
  error: false
}
